/home/user/miniconda3/envs/cml/lib/python3.10/site-packages/sklearn/base.py:376: InconsistentVersionWarning: Trying to unpickle estimator LogisticRegression from version 1.3.2 when using version 1.5.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
number of classes: 7487
Starting evaluation on different task groups...


Task IDs in: [0, 342)

RAG-IM:
	 precision
		Weighted mean:	 0.7516196429126014
		 Mean:		 0.6753073621562077
	 recall
		Weighted mean:	 0.6466929297117976
		 Mean:		 0.5881291439619438
	 f1
		Weighted mean:	 0.6850023898292346
		 Mean:		 0.6059398887663937
	 accuracy
		Weighted mean:	 0.7262077545096413
		 Mean:		 0.6949905163793397

Baseline:
	 precision
		Weighted mean:	 0.7485421100893399
		Mean:		 0.5302669589880833
	 recall
		Weighted mean:	 0.7480821065726726
		Mean:		 0.5689882056555152
	 f1
		Weighted mean:	 0.7412791834945974
		Mean:		 0.5217828716227713
	 accuracy
		Weighted mean:	 0.7538876218121501
		Mean:		 0.5970722056234167


Task IDs in: [342, 1522)

RAG-IM:
	 precision
		Weighted mean:	 0.7695211648180138
		 Mean:		 0.6353444856224345
	 recall
		Weighted mean:	 0.6529323441088147
		 Mean:		 0.55183286131425
	 f1
		Weighted mean:	 0.6953948886486018
		 Mean:		 0.5692100960719418
	 accuracy
		Weighted mean:	 0.7355149266913973
		 Mean:		 0.6734441347035376

Baseline:
	 precision
		Weighted mean:	 0.7718240903385981
		Mean:		 0.5347313269746479
	 recall
		Weighted mean:	 0.7640876170287935
		Mean:		 0.5881565182852274
	 f1
		Weighted mean:	 0.7621511173132389
		Mean:		 0.5313865047489175
	 accuracy
		Weighted mean:	 0.7715509627274333
		Mean:		 0.6114130551377069


Task IDs in: [1522, 2307)
Traceback (most recent call last):
  File "/home/user/RAG_IM/inference_all_subset.py", line 197, in <module>
    acc_all, acc_baseline, ttl_cnt = eval_all(start=start, end=end, verbose=0)
  File "/home/user/RAG_IM/inference_all_subset.py", line 127, in eval_all
    x = np.concatenate([np.ones([X_tests_1[i].shape[0], 1]), X_tests_1[i]], 1).astype(np.float32)
IndexError: list index out of range
